### ISSUE TITLE
Are there any plans to support Wasmer v3.0?

### ISSUE THREAD

**Issue by sergeysova** [fiberplane/fp-bindgen#152]

**Comment by sagacity** [comment]
Yes, we will probably add support in the near future. Are there any specific wasmer 3.0 features you want to use?

**Comment by sagacity** [comment]
Wasmer 3 support has been added in https://github.com/fiberplane/fp-bindgen/pull/157. Feel free to take it for a spin on the `main` branch. Since there are some breaking changes (most notably the `Runtime` methods are now `&mut self`) this will end up being part of an `fp-bindgen 3.0.0` release eventually.

**Comment by sergeysova** [comment]
Awesome!
@sagacity Thank you
